{% set name = "doctr-versions-menu" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/doctr_versions_menu-{{ version }}.tar.gz
  sha256: 8a8d9aa8f9b598491aa5e6d67248a121714f0ab2c817c5d11354fba1398916b4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - doctr-versions-menu = doctr_versions_menu.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - click >=6.7
    - configobj >=5.0.6
    - doctr
    - packaging
    - pyparsing
    - sphinx

test:
  requires:
    - python {{ python_min }}
  imports:
    - doctr_versions_menu

  commands:
    - doctr-versions-menu --help

about:
  home: https://github.com/goerz/doctr_versions_menu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sphinx extension and command to add a versions menu to Doctr-deployed documentation
  doc_url: https://goerz.github.io/doctr_versions_menu
  dev_url: https://github.com/goerz/doctr_versions_menu

extra:
  recipe-maintainers:
    - goerz
