{% set name = "doctr-versions-menu" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/doctr_versions_menu-{{ version }}.tar.gz
  sha256: d49166b7a0a1a0ce14f37a5314d420de69421a1764307f91c9910a02852d7c95

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - doctr-versions-menu = doctr_versions_menu.cli:main

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools

  run:
    - python >=3.5
    - click >=6.7
    - configobj >=5.0.6
    - doctr
    - packaging
    - pyparsing
    - sphinx

test:
  imports:
    - doctr_versions_menu

  commands:
    - doctr-versions-menu --help

about:
  home: https://github.com/goerz/doctr_versions_menu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sphinx extension and command to add a versions menu to Doctr-deployed documentation
  doc_url: https://goerz.github.io/doctr_versions_menu
  dev_url: https://github.com/goerz/doctr_versions_menu

extra:
  recipe-maintainers:
    - hhslepicka
    - goerz
